version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 2512:2512
    links:
      - database
  database:
    image: "postgres"
    expose:
      - 5432
    env_file:
      - .env